version: '3.1'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: krad
      MYSQL_ROOT_PASSWORD: 1115444123
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - 3360:3306
    volumes:
      - ./db/mysql=/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

