database:
  mysql:
    database: krad
    username: root
    password: 1115444123
    host: localhost
    port: 3360
    adabter: mysql
    time_zone: Asia/Tehran
    charset: utf8mb4
   
logger:
  max_age: 720h
  max_size: 20MB
  filename_pattern: "%Y-%m-%dT%H:%M"
  rotation_time: "24h"
  internal_path: "./log"

server:
  host: localhost
  port: 8089